apiVersion: iam.nexus.crossplane.io/v1alpha1
kind: AnonymousAccess
metadata:
  name: anonymous-settings
  namespace: default
spec:
  forProvider:
    enabled: true
    userId: anonymous
    realmName: NexusAuthorizingRealm
  providerConfigRef:
    kind: ProviderConfig
    name: default
