apiVersion: iam.nexus.crossplane.io/v1alpha1
kind: LDAP
metadata:
  name: corporate-ldap
  namespace: default
spec:
  forProvider:
    name: corporate-ldap
    protocol: ldaps
    host: ldap.example.com
    port: 636
    searchBase: dc=example,dc=com
    authScheme: simple
    authUsername: cn=admin,dc=example,dc=com
    authPasswordSecretRef:
      name: ldap-credentials
      namespace: default
      key: password
    userBaseDn: ou=people
    userObjectClass: inetOrgPerson
    userIdAttribute: uid
    userRealNameAttribute: cn
    userEmailAddressAttribute: mail
    ldapGroupsAsRoles: true
    groupType: static
    groupBaseDn: ou=groups
    groupObjectClass: groupOfUniqueNames
    groupIdAttribute: cn
    groupMemberAttribute: uniqueMember
    groupMemberFormat: "uid=${username},ou=people,dc=example,dc=com"
  providerConfigRef:
    kind: ProviderConfig
    name: default
