apiVersion: iam.nexus.crossplane.io/v1alpha1
kind: SecurityRealm
metadata:
  name: nexus-realms
spec:
  forProvider:
    activeRealms:
      - NexusAuthenticatingRealm
      - NexusAuthorizingRealm
      - DockerToken
      - NpmToken
  providerConfigRef:
    kind: ProviderConfig
    name: default
