//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccess) DeepCopyInto(out *AnonymousAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccess.
func (in *AnonymousAccess) DeepCopy() *AnonymousAccess {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymousAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessList) DeepCopyInto(out *AnonymousAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnonymousAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessList.
func (in *AnonymousAccessList) DeepCopy() *AnonymousAccessList {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymousAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessObservation) DeepCopyInto(out *AnonymousAccessObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessObservation.
func (in *AnonymousAccessObservation) DeepCopy() *AnonymousAccessObservation {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessParameters) DeepCopyInto(out *AnonymousAccessParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessParameters.
func (in *AnonymousAccessParameters) DeepCopy() *AnonymousAccessParameters {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessSpec) DeepCopyInto(out *AnonymousAccessSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessSpec.
func (in *AnonymousAccessSpec) DeepCopy() *AnonymousAccessSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessStatus) DeepCopyInto(out *AnonymousAccessStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessStatus.
func (in *AnonymousAccessStatus) DeepCopy() *AnonymousAccessStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmInfo) DeepCopyInto(out *RealmInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmInfo.
func (in *RealmInfo) DeepCopy() *RealmInfo {
	if in == nil {
		return nil
	}
	out := new(RealmInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRealm) DeepCopyInto(out *SecurityRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRealm.
func (in *SecurityRealm) DeepCopy() *SecurityRealm {
	if in == nil {
		return nil
	}
	out := new(SecurityRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRealmList) DeepCopyInto(out *SecurityRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRealmList.
func (in *SecurityRealmList) DeepCopy() *SecurityRealmList {
	if in == nil {
		return nil
	}
	out := new(SecurityRealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRealmObservation) DeepCopyInto(out *SecurityRealmObservation) {
	*out = *in
	if in.AvailableRealms != nil {
		in, out := &in.AvailableRealms, &out.AvailableRealms
		*out = make([]RealmInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRealmObservation.
func (in *SecurityRealmObservation) DeepCopy() *SecurityRealmObservation {
	if in == nil {
		return nil
	}
	out := new(SecurityRealmObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRealmParameters) DeepCopyInto(out *SecurityRealmParameters) {
	*out = *in
	if in.ActiveRealms != nil {
		in, out := &in.ActiveRealms, &out.ActiveRealms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRealmParameters.
func (in *SecurityRealmParameters) DeepCopy() *SecurityRealmParameters {
	if in == nil {
		return nil
	}
	out := new(SecurityRealmParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRealmSpec) DeepCopyInto(out *SecurityRealmSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRealmSpec.
func (in *SecurityRealmSpec) DeepCopy() *SecurityRealmSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityRealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityRealmStatus) DeepCopyInto(out *SecurityRealmStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityRealmStatus.
func (in *SecurityRealmStatus) DeepCopy() *SecurityRealmStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityRealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenConfiguration) DeepCopyInto(out *UserTokenConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenConfiguration.
func (in *UserTokenConfiguration) DeepCopy() *UserTokenConfiguration {
	if in == nil {
		return nil
	}
	out := new(UserTokenConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserTokenConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenConfigurationList) DeepCopyInto(out *UserTokenConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserTokenConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenConfigurationList.
func (in *UserTokenConfigurationList) DeepCopy() *UserTokenConfigurationList {
	if in == nil {
		return nil
	}
	out := new(UserTokenConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserTokenConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenConfigurationObservation) DeepCopyInto(out *UserTokenConfigurationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenConfigurationObservation.
func (in *UserTokenConfigurationObservation) DeepCopy() *UserTokenConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(UserTokenConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenConfigurationParameters) DeepCopyInto(out *UserTokenConfigurationParameters) {
	*out = *in
	if in.ProtectContent != nil {
		in, out := &in.ProtectContent, &out.ProtectContent
		*out = new(bool)
		**out = **in
	}
	if in.ExpirationEnabled != nil {
		in, out := &in.ExpirationEnabled, &out.ExpirationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpirationDays != nil {
		in, out := &in.ExpirationDays, &out.ExpirationDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenConfigurationParameters.
func (in *UserTokenConfigurationParameters) DeepCopy() *UserTokenConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(UserTokenConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenConfigurationSpec) DeepCopyInto(out *UserTokenConfigurationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenConfigurationSpec.
func (in *UserTokenConfigurationSpec) DeepCopy() *UserTokenConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(UserTokenConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTokenConfigurationStatus) DeepCopyInto(out *UserTokenConfigurationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTokenConfigurationStatus.
func (in *UserTokenConfigurationStatus) DeepCopy() *UserTokenConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(UserTokenConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
