//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptConfig) DeepCopyInto(out *AptConfig) {
	*out = *in
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = new(string)
		**out = **in
	}
	if in.Flat != nil {
		in, out := &in.Flat, &out.Flat
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptConfig.
func (in *AptConfig) DeepCopy() *AptConfig {
	if in == nil {
		return nil
	}
	out := new(AptConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptSigningConfig) DeepCopyInto(out *AptSigningConfig) {
	*out = *in
	if in.Passphrase != nil {
		in, out := &in.Passphrase, &out.Passphrase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptSigningConfig.
func (in *AptSigningConfig) DeepCopy() *AptSigningConfig {
	if in == nil {
		return nil
	}
	out := new(AptSigningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
	if in.AccountKeySecretRef != nil {
		in, out := &in.AccountKeySecretRef, &out.AccountKeySecretRef
		*out = new(v2.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStore) DeepCopyInto(out *BlobStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStore.
func (in *BlobStore) DeepCopy() *BlobStore {
	if in == nil {
		return nil
	}
	out := new(BlobStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlobStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreList) DeepCopyInto(out *BlobStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlobStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreList.
func (in *BlobStoreList) DeepCopy() *BlobStoreList {
	if in == nil {
		return nil
	}
	out := new(BlobStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlobStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreObservation) DeepCopyInto(out *BlobStoreObservation) {
	*out = *in
	if in.AvailableSpaceInBytes != nil {
		in, out := &in.AvailableSpaceInBytes, &out.AvailableSpaceInBytes
		*out = new(int64)
		**out = **in
	}
	if in.TotalSizeInBytes != nil {
		in, out := &in.TotalSizeInBytes, &out.TotalSizeInBytes
		*out = new(int64)
		**out = **in
	}
	if in.BlobCount != nil {
		in, out := &in.BlobCount, &out.BlobCount
		*out = new(int64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.SoftQuotaType != nil {
		in, out := &in.SoftQuotaType, &out.SoftQuotaType
		*out = new(string)
		**out = **in
	}
	if in.SoftQuotaLimit != nil {
		in, out := &in.SoftQuotaLimit, &out.SoftQuotaLimit
		*out = new(int64)
		**out = **in
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.BucketRegion != nil {
		in, out := &in.BucketRegion, &out.BucketRegion
		*out = new(string)
		**out = **in
	}
	if in.BucketPrefix != nil {
		in, out := &in.BucketPrefix, &out.BucketPrefix
		*out = new(string)
		**out = **in
	}
	if in.AzureAccountName != nil {
		in, out := &in.AzureAccountName, &out.AzureAccountName
		*out = new(string)
		**out = **in
	}
	if in.AzureContainerName != nil {
		in, out := &in.AzureContainerName, &out.AzureContainerName
		*out = new(string)
		**out = **in
	}
	if in.AzureAuthenticationMethod != nil {
		in, out := &in.AzureAuthenticationMethod, &out.AzureAuthenticationMethod
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreObservation.
func (in *BlobStoreObservation) DeepCopy() *BlobStoreObservation {
	if in == nil {
		return nil
	}
	out := new(BlobStoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreParameters) DeepCopyInto(out *BlobStoreParameters) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.SoftQuota != nil {
		in, out := &in.SoftQuota, &out.SoftQuota
		*out = new(SoftQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.S3Config != nil {
		in, out := &in.S3Config, &out.S3Config
		*out = new(S3Config)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureConfig != nil {
		in, out := &in.AzureConfig, &out.AzureConfig
		*out = new(AzureConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreParameters.
func (in *BlobStoreParameters) DeepCopy() *BlobStoreParameters {
	if in == nil {
		return nil
	}
	out := new(BlobStoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreSpec) DeepCopyInto(out *BlobStoreSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreSpec.
func (in *BlobStoreSpec) DeepCopy() *BlobStoreSpec {
	if in == nil {
		return nil
	}
	out := new(BlobStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobStoreStatus) DeepCopyInto(out *BlobStoreStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobStoreStatus.
func (in *BlobStoreStatus) DeepCopy() *BlobStoreStatus {
	if in == nil {
		return nil
	}
	out := new(BlobStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BowerConfig) DeepCopyInto(out *BowerConfig) {
	*out = *in
	if in.RewritePackageUrls != nil {
		in, out := &in.RewritePackageUrls, &out.RewritePackageUrls
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BowerConfig.
func (in *BowerConfig) DeepCopy() *BowerConfig {
	if in == nil {
		return nil
	}
	out := new(BowerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CargoConfig) DeepCopyInto(out *CargoConfig) {
	*out = *in
	if in.RequireAuthentication != nil {
		in, out := &in.RequireAuthentication, &out.RequireAuthentication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CargoConfig.
func (in *CargoConfig) DeepCopy() *CargoConfig {
	if in == nil {
		return nil
	}
	out := new(CargoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerConfig) DeepCopyInto(out *DockerConfig) {
	*out = *in
	if in.V1Enabled != nil {
		in, out := &in.V1Enabled, &out.V1Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ForceBasicAuth != nil {
		in, out := &in.ForceBasicAuth, &out.ForceBasicAuth
		*out = new(bool)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(int32)
		**out = **in
	}
	if in.HTTPSPort != nil {
		in, out := &in.HTTPSPort, &out.HTTPSPort
		*out = new(int32)
		**out = **in
	}
	if in.Subdomain != nil {
		in, out := &in.Subdomain, &out.Subdomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerConfig.
func (in *DockerConfig) DeepCopy() *DockerConfig {
	if in == nil {
		return nil
	}
	out := new(DockerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerProxyConfig) DeepCopyInto(out *DockerProxyConfig) {
	*out = *in
	if in.IndexType != nil {
		in, out := &in.IndexType, &out.IndexType
		*out = new(string)
		**out = **in
	}
	if in.IndexURL != nil {
		in, out := &in.IndexURL, &out.IndexURL
		*out = new(string)
		**out = **in
	}
	if in.CacheForeignLayers != nil {
		in, out := &in.CacheForeignLayers, &out.CacheForeignLayers
		*out = new(bool)
		**out = **in
	}
	if in.ForeignLayerUrlWhitelist != nil {
		in, out := &in.ForeignLayerUrlWhitelist, &out.ForeignLayerUrlWhitelist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerProxyConfig.
func (in *DockerProxyConfig) DeepCopy() *DockerProxyConfig {
	if in == nil {
		return nil
	}
	out := new(DockerProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupConfig) DeepCopyInto(out *GroupConfig) {
	*out = *in
	if in.MemberNames != nil {
		in, out := &in.MemberNames, &out.MemberNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WritableMember != nil {
		in, out := &in.WritableMember, &out.WritableMember
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupConfig.
func (in *GroupConfig) DeepCopy() *GroupConfig {
	if in == nil {
		return nil
	}
	out := new(GroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientAuthentication) DeepCopyInto(out *HTTPClientAuthentication) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.NTLMHost != nil {
		in, out := &in.NTLMHost, &out.NTLMHost
		*out = new(string)
		**out = **in
	}
	if in.NTLMDomain != nil {
		in, out := &in.NTLMDomain, &out.NTLMDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientAuthentication.
func (in *HTTPClientAuthentication) DeepCopy() *HTTPClientAuthentication {
	if in == nil {
		return nil
	}
	out := new(HTTPClientAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientConfig) DeepCopyInto(out *HTTPClientConfig) {
	*out = *in
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.AutoBlock != nil {
		in, out := &in.AutoBlock, &out.AutoBlock
		*out = new(bool)
		**out = **in
	}
	if in.Connection != nil {
		in, out := &in.Connection, &out.Connection
		*out = new(HTTPClientConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(HTTPClientAuthentication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientConfig.
func (in *HTTPClientConfig) DeepCopy() *HTTPClientConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPClientConnection) DeepCopyInto(out *HTTPClientConnection) {
	*out = *in
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int32)
		**out = **in
	}
	if in.UserAgentSuffix != nil {
		in, out := &in.UserAgentSuffix, &out.UserAgentSuffix
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int32)
		**out = **in
	}
	if in.EnableCircularRedirects != nil {
		in, out := &in.EnableCircularRedirects, &out.EnableCircularRedirects
		*out = new(bool)
		**out = **in
	}
	if in.EnableCookies != nil {
		in, out := &in.EnableCookies, &out.EnableCookies
		*out = new(bool)
		**out = **in
	}
	if in.UseTrustStore != nil {
		in, out := &in.UseTrustStore, &out.UseTrustStore
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPClientConnection.
func (in *HTTPClientConnection) DeepCopy() *HTTPClientConnection {
	if in == nil {
		return nil
	}
	out := new(HTTPClientConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MavenConfig) DeepCopyInto(out *MavenConfig) {
	*out = *in
	if in.VersionPolicy != nil {
		in, out := &in.VersionPolicy, &out.VersionPolicy
		*out = new(string)
		**out = **in
	}
	if in.LayoutPolicy != nil {
		in, out := &in.LayoutPolicy, &out.LayoutPolicy
		*out = new(string)
		**out = **in
	}
	if in.ContentDisposition != nil {
		in, out := &in.ContentDisposition, &out.ContentDisposition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MavenConfig.
func (in *MavenConfig) DeepCopy() *MavenConfig {
	if in == nil {
		return nil
	}
	out := new(MavenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegativeCacheConfig) DeepCopyInto(out *NegativeCacheConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TimeToLive != nil {
		in, out := &in.TimeToLive, &out.TimeToLive
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegativeCacheConfig.
func (in *NegativeCacheConfig) DeepCopy() *NegativeCacheConfig {
	if in == nil {
		return nil
	}
	out := new(NegativeCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpmConfig) DeepCopyInto(out *NpmConfig) {
	*out = *in
	if in.RemoveNonCataloged != nil {
		in, out := &in.RemoveNonCataloged, &out.RemoveNonCataloged
		*out = new(bool)
		**out = **in
	}
	if in.RemoveQuarantined != nil {
		in, out := &in.RemoveQuarantined, &out.RemoveQuarantined
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpmConfig.
func (in *NpmConfig) DeepCopy() *NpmConfig {
	if in == nil {
		return nil
	}
	out := new(NpmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NugetProxyConfig) DeepCopyInto(out *NugetProxyConfig) {
	*out = *in
	if in.QueryCacheItemMaxAge != nil {
		in, out := &in.QueryCacheItemMaxAge, &out.QueryCacheItemMaxAge
		*out = new(int32)
		**out = **in
	}
	if in.NugetVersion != nil {
		in, out := &in.NugetVersion, &out.NugetVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NugetProxyConfig.
func (in *NugetProxyConfig) DeepCopy() *NugetProxyConfig {
	if in == nil {
		return nil
	}
	out := new(NugetProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.ContentMaxAge != nil {
		in, out := &in.ContentMaxAge, &out.ContentMaxAge
		*out = new(int32)
		**out = **in
	}
	if in.MetadataMaxAge != nil {
		in, out := &in.MetadataMaxAge, &out.MetadataMaxAge
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryCleanup) DeepCopyInto(out *RepositoryCleanup) {
	*out = *in
	if in.PolicyNames != nil {
		in, out := &in.PolicyNames, &out.PolicyNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryCleanup.
func (in *RepositoryCleanup) DeepCopy() *RepositoryCleanup {
	if in == nil {
		return nil
	}
	out := new(RepositoryCleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryObservation) DeepCopyInto(out *RepositoryObservation) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryObservation.
func (in *RepositoryObservation) DeepCopy() *RepositoryObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryParameters) DeepCopyInto(out *RepositoryParameters) {
	*out = *in
	if in.Online != nil {
		in, out := &in.Online, &out.Online
		*out = new(bool)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(RepositoryStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.Cleanup != nil {
		in, out := &in.Cleanup, &out.Cleanup
		*out = new(RepositoryCleanup)
		(*in).DeepCopyInto(*out)
	}
	if in.Maven != nil {
		in, out := &in.Maven, &out.Maven
		*out = new(MavenConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DockerProxy != nil {
		in, out := &in.DockerProxy, &out.DockerProxy
		*out = new(DockerProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NegativeCache != nil {
		in, out := &in.NegativeCache, &out.NegativeCache
		*out = new(NegativeCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPClient != nil {
		in, out := &in.HTTPClient, &out.HTTPClient
		*out = new(HTTPClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(GroupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Npm != nil {
		in, out := &in.Npm, &out.Npm
		*out = new(NpmConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Apt != nil {
		in, out := &in.Apt, &out.Apt
		*out = new(AptConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AptSigning != nil {
		in, out := &in.AptSigning, &out.AptSigning
		*out = new(AptSigningConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Yum != nil {
		in, out := &in.Yum, &out.Yum
		*out = new(YumConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.YumSigning != nil {
		in, out := &in.YumSigning, &out.YumSigning
		*out = new(YumSigningConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NugetProxy != nil {
		in, out := &in.NugetProxy, &out.NugetProxy
		*out = new(NugetProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bower != nil {
		in, out := &in.Bower, &out.Bower
		*out = new(BowerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cargo != nil {
		in, out := &in.Cargo, &out.Cargo
		*out = new(CargoConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RoutingRule != nil {
		in, out := &in.RoutingRule, &out.RoutingRule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryParameters.
func (in *RepositoryParameters) DeepCopy() *RepositoryParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStorage) DeepCopyInto(out *RepositoryStorage) {
	*out = *in
	if in.StrictContentTypeValidation != nil {
		in, out := &in.StrictContentTypeValidation, &out.StrictContentTypeValidation
		*out = new(bool)
		**out = **in
	}
	if in.WritePolicy != nil {
		in, out := &in.WritePolicy, &out.WritePolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStorage.
func (in *RepositoryStorage) DeepCopy() *RepositoryStorage {
	if in == nil {
		return nil
	}
	out := new(RepositoryStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.ExpirationDays != nil {
		in, out := &in.ExpirationDays, &out.ExpirationDays
		*out = new(int32)
		**out = **in
	}
	if in.AccessKeyIDSecretRef != nil {
		in, out := &in.AccessKeyIDSecretRef, &out.AccessKeyIDSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.SecretAccessKeySecretRef != nil {
		in, out := &in.SecretAccessKeySecretRef, &out.SecretAccessKeySecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AssumeRole != nil {
		in, out := &in.AssumeRole, &out.AssumeRole
		*out = new(string)
		**out = **in
	}
	if in.SessionTokenSecretRef != nil {
		in, out := &in.SessionTokenSecretRef, &out.SessionTokenSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.ForcePathStyle != nil {
		in, out := &in.ForcePathStyle, &out.ForcePathStyle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftQuota) DeepCopyInto(out *SoftQuota) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftQuota.
func (in *SoftQuota) DeepCopy() *SoftQuota {
	if in == nil {
		return nil
	}
	out := new(SoftQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumConfig) DeepCopyInto(out *YumConfig) {
	*out = *in
	if in.RepodataDepth != nil {
		in, out := &in.RepodataDepth, &out.RepodataDepth
		*out = new(int32)
		**out = **in
	}
	if in.DeployPolicy != nil {
		in, out := &in.DeployPolicy, &out.DeployPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumConfig.
func (in *YumConfig) DeepCopy() *YumConfig {
	if in == nil {
		return nil
	}
	out := new(YumConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YumSigningConfig) DeepCopyInto(out *YumSigningConfig) {
	*out = *in
	if in.Keypair != nil {
		in, out := &in.Keypair, &out.Keypair
		*out = new(string)
		**out = **in
	}
	if in.Passphrase != nil {
		in, out := &in.Passphrase, &out.Passphrase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YumSigningConfig.
func (in *YumSigningConfig) DeepCopy() *YumSigningConfig {
	if in == nil {
		return nil
	}
	out := new(YumSigningConfig)
	in.DeepCopyInto(out)
	return out
}
