---
apiVersion: content.nexus.crossplane.io/v1alpha1
kind: ContentSelector
metadata:
  name: maven-releases
  namespace: default
spec:
  forProvider:
    name: maven-releases
    description: "Selector for Maven release artifacts"
    expression: format == "maven2" and path =^ "/releases/"
  providerConfigRef:
    kind: ProviderConfig
    name: default
