---
# Docker hosted repository example
apiVersion: content.nexus.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: docker-hosted
  namespace: default
spec:
  forProvider:
    name: docker-hosted
    format: docker
    type: hosted
    online: true
    docker:
      httpPort: 8082
      httpsPort: 8083
      forceBasicAuth: true
      v1Enabled: false
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
      writePolicy: ALLOW
  providerConfigRef:
    kind: ProviderConfig
    name: default
