---
# P2 (Eclipse plugin) proxy repository example
apiVersion: content.nexus.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: eclipse-p2-proxy
  namespace: default
spec:
  forProvider:
    name: eclipse-p2-proxy
    format: p2
    type: proxy
    online: true
    proxy:
      remoteUrl: https://download.eclipse.org/releases/latest
      contentMaxAge: 1440
      metadataMaxAge: 1440
    negativeCache:
      enabled: true
      timeToLive: 1440
    httpClient:
      blocked: false
      autoBlock: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
  providerConfigRef:
    kind: ProviderConfig
    name: default
