---
# NPM hosted repository example
apiVersion: content.nexus.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: npm-hosted
  namespace: default
spec:
  forProvider:
    name: npm-hosted
    format: npm
    type: hosted
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
      writePolicy: ALLOW
  providerConfigRef:
    kind: ProviderConfig
    name: default
