---
# Maven2 group repository example
apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: maven-public
  namespace: default
spec:
  forProvider:
    name: maven-public
    format: maven2
    type: group
    online: true
    group:
      memberNames:
        - maven-releases
        - maven-snapshots
        - maven-central-proxy
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
  providerConfigRef:
    kind: ProviderConfig
    name: default
