//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfiguration) DeepCopyInto(out *EmailConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfiguration.
func (in *EmailConfiguration) DeepCopy() *EmailConfiguration {
	if in == nil {
		return nil
	}
	out := new(EmailConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfigurationList) DeepCopyInto(out *EmailConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmailConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfigurationList.
func (in *EmailConfigurationList) DeepCopy() *EmailConfigurationList {
	if in == nil {
		return nil
	}
	out := new(EmailConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmailConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfigurationObservation) DeepCopyInto(out *EmailConfigurationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfigurationObservation.
func (in *EmailConfigurationObservation) DeepCopy() *EmailConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(EmailConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfigurationParameters) DeepCopyInto(out *EmailConfigurationParameters) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.SubjectPrefix != nil {
		in, out := &in.SubjectPrefix, &out.SubjectPrefix
		*out = new(string)
		**out = **in
	}
	if in.StartTlsEnabled != nil {
		in, out := &in.StartTlsEnabled, &out.StartTlsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTlsRequired != nil {
		in, out := &in.StartTlsRequired, &out.StartTlsRequired
		*out = new(bool)
		**out = **in
	}
	if in.SslOnConnectEnabled != nil {
		in, out := &in.SslOnConnectEnabled, &out.SslOnConnectEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SslServerIdentityCheckEnabled != nil {
		in, out := &in.SslServerIdentityCheckEnabled, &out.SslServerIdentityCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfigurationParameters.
func (in *EmailConfigurationParameters) DeepCopy() *EmailConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(EmailConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfigurationSpec) DeepCopyInto(out *EmailConfigurationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfigurationSpec.
func (in *EmailConfigurationSpec) DeepCopy() *EmailConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(EmailConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfigurationStatus) DeepCopyInto(out *EmailConfigurationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfigurationStatus.
func (in *EmailConfigurationStatus) DeepCopy() *EmailConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(EmailConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
