// gen-managed generates the managed.go file with Crossplane interface implementations.
// This eliminates repetitive boilerplate by generating the same 10 methods for each resource.
//
// Usage: go run hack/gen-managed/main.go > apis/v1alpha1/managed.go
package main

import (
	"fmt"
	"os"
	"text/template"
)

// ManagedResource represents a Crossplane managed resource that needs interface implementations.
type ManagedResource struct {
	Name string
}

// managedResources is the list of all managed resources in this provider.
// To add a new resource, simply add its name to this list and run `go generate`.
var managedResources = []ManagedResource{
	{Name: "BlobStore"},
	{Name: "Repository"},
	{Name: "User"},
	{Name: "Role"},
	{Name: "ContentSelector"},
	{Name: "Privilege"},
	{Name: "SecurityRealm"},
	{Name: "AnonymousAccess"},
	{Name: "SAML"},
	{Name: "LDAP"},
	{Name: "UserTokenConfiguration"},
}

const fileTemplate = `// Code generated by hack/gen-managed/main.go. DO NOT EDIT.
// To regenerate, run: go generate ./apis/v1alpha1/...

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

{{range .Resources}}
// {{.Name}} managed resource interface implementations

// GetCondition of this {{.Name}}.
func (mg *{{.Name}}) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// SetConditions of this {{.Name}}.
func (mg *{{.Name}}) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// GetDeletionPolicy of this {{.Name}}.
func (mg *{{.Name}}) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// SetDeletionPolicy of this {{.Name}}.
func (mg *{{.Name}}) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// GetManagementPolicies of this {{.Name}}.
func (mg *{{.Name}}) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// SetManagementPolicies of this {{.Name}}.
func (mg *{{.Name}}) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// GetProviderConfigReference of this {{.Name}}.
func (mg *{{.Name}}) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// SetProviderConfigReference of this {{.Name}}.
func (mg *{{.Name}}) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// GetPublishConnectionDetailsTo of this {{.Name}}.
func (mg *{{.Name}}) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// SetPublishConnectionDetailsTo of this {{.Name}}.
func (mg *{{.Name}}) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// GetWriteConnectionSecretToReference of this {{.Name}}.
func (mg *{{.Name}}) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetWriteConnectionSecretToReference of this {{.Name}}.
func (mg *{{.Name}}) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
{{end}}
// ProviderConfigUsage interface implementations (different pattern - non-pointer references)

// GetProviderConfigReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) GetProviderConfigReference() xpv1.Reference {
	return p.ProviderConfigUsage.ProviderConfigReference
}

// SetProviderConfigReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) SetProviderConfigReference(r xpv1.Reference) {
	p.ProviderConfigUsage.ProviderConfigReference = r
}

// GetResourceReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) GetResourceReference() xpv1.TypedReference {
	return p.ProviderConfigUsage.ResourceReference
}

// SetResourceReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) SetResourceReference(r xpv1.TypedReference) {
	p.ProviderConfigUsage.ResourceReference = r
}
`

type templateData struct {
	Resources []ManagedResource
}

func main() {
	tmpl, err := template.New("managed").Parse(fileTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	data := templateData{
		Resources: managedResources,
	}

	if err := tmpl.Execute(os.Stdout, data); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}
}
