---
apiVersion: instance.nexus.crossplane.io/v1alpha1
kind: Capability
metadata:
  name: docker-bearer-token
spec:
  forProvider:
    typeId: DockerBearerTokenRealm
    enabled: true
    notes: "Enable Docker Bearer Token authentication"
    properties: {}
  providerConfigRef:
    kind: ProviderConfig
    name: default
