apiVersion: nexus.crossplane.io/v1alpha1
kind: AnonymousAccess
metadata:
  name: anonymous-settings
spec:
  forProvider:
    enabled: true
    userId: anonymous
    realmName: NexusAuthorizingRealm
  providerConfigRef:
    kind: ProviderConfig
    name: nexus-provider-config
