---
apiVersion: content.nexus.crossplane.io/v1alpha1
kind: CleanupPolicy
metadata:
  name: example-cleanup-policy
spec:
  forProvider:
    name: example-cleanup-policy
    format: maven2
    notes: "Remove Maven artifacts older than 90 days that have not been downloaded in 30 days"
    criteriaLastBlobUpdated: 90
    criteriaLastDownloaded: 30
    criteriaReleaseType: RELEASES
  providerConfigRef:
    name: default
