apiVersion: nexus.crossplane.io/v1alpha1
kind: SecuritySSLTruststore
metadata:
  name: ldap-server-cert
spec:
  forProvider:
    pem: |
      -----BEGIN CERTIFICATE-----
      MIIBkTCB+wIJALRiMLAh0ERXMA0GCSqGSIb3DQEBBQUAMBExDzANBgNVBAMM
      BnRlc3RDQTAYHDI1MDEwMTAwMDAwMFoYDzIwNTAwMTAxMDAwMDAwWjARMQ8w
      DQYDVQQDDAZ0ZXN0Q0EwXDANBgkqhkiG9w0BAQEFAANLADBIAkEA0Z3VS5JJ
      ...your certificate content here...
      -----END CERTIFICATE-----
  providerConfigRef:
    name: nexus-provider-config
