---
# Secret containing user password
apiVersion: v1
kind: Secret
metadata:
  name: nexus-user-password
  namespace: crossplane-system
type: Opaque
stringData:
  password: "securePassword123!"
---
# Nexus User example
apiVersion: nexus.crossplane.io/v1alpha1
kind: User
metadata:
  name: developer-user
  namespace: default
spec:
  forProvider:
    userId: developer
    firstName: John
    lastName: Developer
    emailAddress: john.developer@example.com
    status: active  # active or disabled
    roles:
      - nx-repository-view-maven2-*-read
      - nx-repository-view-npm-*-read
    passwordSecretRef:
      name: nexus-user-password
      namespace: crossplane-system
      key: password
  providerConfigRef:
    kind: ProviderConfig
    name: default
