---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "url": "http://nexus.nexus.svc.cluster.local:8081",
      "username": "admin",
      "password": "admin123",
      "insecure": true
    }
---
apiVersion: nexus.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: nexus-credentials
      namespace: crossplane-system
      key: ""
