apiVersion: nexus.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: e2e-test-helm-proxy
  namespace: default
spec:
  forProvider:
    name: e2e-test-helm-proxy
    format: helm
    type: proxy
    online: true
    proxy:
      remoteUrl: https://charts.helm.sh/stable
      contentMaxAge: 1440
      metadataMaxAge: 1440
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
    httpClient:
      blocked: false
      autoBlock: true
    negativeCache:
      enabled: true
      timeToLive: 1440
  providerConfigRef:
    name: default
