apiVersion: repository.nexus.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: e2e-test-maven-group
  namespace: default
spec:
  forProvider:
    name: e2e-test-maven-group
    format: maven2
    type: group
    online: true
    maven:
      versionPolicy: RELEASE
      layoutPolicy: STRICT
    group:
      memberNames:
        - e2e-group-maven-hosted
        - e2e-group-maven-proxy
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
  providerConfigRef:
    kind: ProviderConfig
    name: default
