apiVersion: nexus.crossplane.io/v1alpha1
kind: Role
metadata:
  name: e2e-test-role
  namespace: default
spec:
  forProvider:
    id: e2e-test-role
    name: E2E Test Role
    description: "Role created by e2e tests"
    privileges:
      - nx-repository-view-*-*-browse
      - nx-repository-view-*-*-read
  providerConfigRef:
    name: default
