apiVersion: nexus.crossplane.io/v1alpha1
kind: User
metadata:
  name: e2e-test-user
  namespace: default
spec:
  forProvider:
    userId: e2e-test-user
    firstName: E2E
    lastName: TestUser
    emailAddress: e2e-test@example.com
    status: active
    roles:
      - nx-anonymous
    passwordSecretRef:
      name: e2e-test-user-password
      namespace: default
      key: password
  providerConfigRef:
    name: default
